# Generated by Django 5.1.1 on 2024-09-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Project Name')),
                ('desc', models.TextField(verbose_name='Description of project')),
                ('img', models.ImageField(upload_to='image', verbose_name='image')),
                ('srclink', models.CharField(max_length=200, verbose_name='Source code link')),
                ('cat', models.CharField(choices=[('front end', 'Front End Project'), ('back end', 'Back End Project'), ('full stack', 'Full Stack Web Project')], max_length=200, verbose_name='Type of project')),
            ],
        ),
    ]
