# Generated by Django 5.1.1 on 2024-10-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech',
            field=models.TextField(default='Python', verbose_name='Technologies used'),
        ),
    ]
